#!/bin/bash

set -e -o pipefail

echo "==> Running linters..."
# gometalinter --disable=gotype --vendor --deadline 30s --fast --errors --severity=golint:error ./...
gometalinter --disable=gotype --vendor --deadline 30s --fast --errors ./...
swagger validate ./swagger/swagger.yml
